//
//  AlgebraUnit1.swift
//  Delta
//
//  Created by Desire on 2026-05-26.
//


import SwiftUI
import Foundation
import Combine
import TestCreation

class AlgebraUnit1: Package, ObservableObject {
    func saveQuestion(question: TestCreation.Question) -> TestCreation.DescriptionOfQuestion {
        DescriptionOfQuestion(ownerInternalName: internalName, question: question)
    }
    func loadQuestion(descriptionOfQuestion: TestCreation.DescriptionOfQuestion) -> TestCreation.Question {
        createQuestion()
    }
    
    
    var publicName: String = "Grade 9 Linear Algebra Practice"
    
    var internalName: String = "algebraUnit1"
    
    var packageDescription: String = """
    This package covers core algebraic mechanics, including simplifying like terms, the distributive property, solving multi-step linear equations, and modeling linear word problems.
    
    Perfect for building foundational computational fluency.
    Generated by Gemini
    """
    
    var id = UUID()
    
    @Published var allChangbleBools: [boolSetting] = [boolSetting(bool: false, name: "Randomize questions?")]
    
    @Published var numberOfQuestionsMadePerSection: Int = 20
    
    @Published var allChangbleInts: [intSetting] = [intSetting(int: 20, name: "Number of questions per section")]
    
    @Published var allChangbleDoubles: [doubleSetting] = []
  
    var shuffledCases: [allQuestions] = []
    var randomizeQuestions: Bool = false
    var generatedAllCases: Bool = false
    var questionNum: Int = 0
    
    func updateInternalSettings() {
        numberOfQuestionsMadePerSection = allChangbleInts[0].int
        randomizeQuestions = allChangbleBools[0].bool
    }
    
    func createSection(numOfQuestions: Int) -> [TestCreation.Question] {
        var allQuestionsMade: [Question] = []
        let limit = min(numberOfQuestionsMadePerSection, loadAllCases().count)
        
        for _ in 0..<limit {
            allQuestionsMade.append(createQuestion())
        }
        questionNum = 0
        return allQuestionsMade
    }
    
    func loadAllCases() -> [allQuestions] {
        if !generatedAllCases {
            shuffledCases = allQuestions.allCases
            generatedAllCases = true
        }
        
        if randomizeQuestions {
            shuffledCases.shuffle()
        } else {
            shuffledCases = allQuestions.allCases
        }
        
        return shuffledCases
    }
    
    func loadAllQuestions() -> [lightQuestion] {
        var allQuestionsLoaded: [lightQuestion] = []
        for question in allQuestions.allCases {
            allQuestionsLoaded.append(question.lightQuestion)
        }
        return allQuestionsLoaded
    }
    
    func createQuestion() -> TestCreation.Question {
        let cases = loadAllCases()
        if cases.isEmpty {
            let emptyContent = QuestionContent { VStack { Text("No algebra questions loaded") } }
            return Question(creator: self.id, questionName: "", questionType: .text, questionText: "Empty", questionContent: emptyContent, questionContentSizeX: 500, questionContentSizeY: 500, questionAnswer: "None")
        }
        
        if self.questionNum >= cases.count {
            self.questionNum = 0
        }
        
        let currentCase = cases[questionNum]
        
        // Handle math type initialization versus text type initialization
        let trueQuestion: Question
        if currentCase.questionType == .math {
            trueQuestion = Question(
                creator: self.id, questionName: "",
                questionType: .math,
                questionText: currentCase.questionWords,
                questionContent: currentCase.questionContent,
                questionContentSizeX: 500,
                questionContentSizeY: 500,
                questionAnswer: ""//currentCase.mathAnswer
            )
        } else {
            trueQuestion = Question(
                creator: self.id, questionName: "",
                questionType: .text,
                questionText: currentCase.questionWords,
                questionContent: currentCase.questionContent,
                questionContentSizeX: 500,
                questionContentSizeY: 500,
                questionAnswer: currentCase.textAnswer
            )
        }
        
        self.questionNum += 1
        return trueQuestion
    }
    
    func filterAnswer(answer: String) -> String {
        return answer.lowercased().trimmingCharacters(in: .whitespacesAndNewlines).replacingOccurrences(of: " ", with: "")
    }
    
    enum allQuestions: CaseIterable {
        // MARK: - Combining Like Terms
        case simplifyBasic
        case simplifyWithExponents
        case simplifyMixedVariables
        
        // MARK: - Distributive Property
        case distributeSingle
        case distributeNegative
        case distributeAndSimplify
        
        // MARK: - Solving Linear Equations
        case solveOneStepAdd
        case solveOneStepMultiply
        case solveTwoStep
        case solveVariablesBothSides
        case solveWithFraction
        
        // MARK: - Algebraic Word Modeling
        case wordProblemAges
        case wordProblemTaxi
        
        var questionType: QuestionType {
            switch self {
            case .solveOneStepAdd, .solveOneStepMultiply, .solveTwoStep, .solveVariablesBothSides, .solveWithFraction:
                return .math
            default:
                return .text
            }
        }

        var questionWords: String {
            switch self {
            case .simplifyBasic: return "Simplify the expression by collecting like terms: 3x + 5 + 7x - 2"
            case .simplifyWithExponents: return "Simplify the expression: 4x² + 3x - 2x² + 5x"
            case .simplifyMixedVariables: return "Simplify the expression: 2a + 3b - a + 4b + 5"
            case .distributeSingle: return "Expand the expression using the distributive property: 3(2x + 4)"
            case .distributeNegative: return "Expand the expression: -2(4x - 5)"
            case .distributeAndSimplify: return "Expand and fully simplify: 4(x + 2) + 3(2x - 1)"
            case .solveOneStepAdd: return "Solve for x using balanced equations."
            case .solveOneStepMultiply: return "Solve for x by isolating the variable."
            case .solveTwoStep: return "Solve for the missing variable x."
            case .solveVariablesBothSides: return "Isolate the variable x to find its value."
            case .solveWithFraction: return "Clear the denominator to isolate x."
            case .wordProblemAges: return "Sarah is 3 years older than twice Alex's age. If the sum of their ages is 27, write an equation modeling this using 'a' for Alex's age."
            case .wordProblemTaxi: return "A taxi company charges a flat fee of $4.00 plus $1.50 per kilometer driven. Write an algebraic expression representing the total cost for 'k' kilometers."
            }
        }
        
        var questionContent: QuestionContent {
            switch self {
            case .simplifyBasic, .simplifyWithExponents, .simplifyMixedVariables:
                return QuestionContent {
                    HStack(spacing: 12) {
                        Image(systemName: "circle.grid.cross.fill")
                            .foregroundColor(.accentColor)
                        Text("Rule: You can only add or subtract terms that share the exact same variable and exponent layout.")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                    .padding(10)
                    .background(Color(.secondarySystemFill))
                    .cornerRadius(8)
                }
                
            case .distributeSingle, .distributeNegative, .distributeAndSimplify:
                return QuestionContent {
                    VStack(alignment: .leading, spacing: 6) {
                        Text("Distributive Multiplier Map:")
                            .font(.caption).bold()
                        Text("a(b + c)  ➜  (a × b) + (a × c)")
                            .font(.system(.footnote, design: .monospaced))
                            .foregroundColor(.secondary)
                    }
                    .padding(8)
                    .background(Color(.secondarySystemFill))
                    .cornerRadius(6)
                }
                
            case .solveOneStepAdd:
                return QuestionContent {
                    Text("x + 7 = 15")
                        .font(.system(.title, design: .monospaced)).bold()
                        .padding()
                }
                
            case .solveOneStepMultiply:
                return QuestionContent {
                    Text("4x = 24")
                        .font(.system(.title, design: .monospaced)).bold()
                        .padding()
                }
                
            case .solveTwoStep:
                return QuestionContent {
                    Text("3x - 5 = 16")
                        .font(.system(.title, design: .monospaced)).bold()
                        .padding()
                }
                
            case .solveVariablesBothSides:
                return QuestionContent {
                    Text("5x + 4 = 2x + 13")
                        .font(.system(.title, design: .monospaced)).bold()
                        .padding()
                }
                
            case .solveWithFraction:
                return QuestionContent {
                    HStack(spacing: 4) {
                        VStack(spacing: 2) {
                            Text("x")
                                .font(.system(.title, design: .monospaced)).bold()
                            Divider().frame(width: 30, height: 2).background(Color.primary)
                            Text("3")
                                .font(.system(.title, design: .monospaced)).bold()
                        }
                        Text("+ 2 = 7")
                            .font(.system(.title, design: .monospaced)).bold()
                    }
                    .padding()
                }
                
            default:
                return QuestionContent {
                    VStack { }
                }
            }
        }
        
        var textAnswer: String {
            switch self {
            case .simplifyBasic: return "10x+3"
            case .simplifyWithExponents: return "2x²+8x"
            case .simplifyMixedVariables: return "a+7b+5"
            case .distributeSingle: return "6x+12"
            case .distributeNegative: return "-8x+10"
            case .distributeAndSimplify: return "10x+5"
            case .wordProblemAges: return "2a+3+a=27"
            case .wordProblemTaxi: return "4.00+1.50k"
            default: return ""
            }
        }
        
        var mathAnswer: mathEquationBlueprint {
            switch self {
            case .solveOneStepAdd:
                // x = 8
                return mathEquationBlueprint(
                    leftSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "x", bottomBase: "1", squareRoot: false)])],
                    relation: .equal,
                    rightSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "8", bottomBase: "1", squareRoot: false)])]
                )
            case .solveOneStepMultiply:
                // x = 6
                return mathEquationBlueprint(
                    leftSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "x", bottomBase: "1", squareRoot: false)])],
                    relation: .equal,
                    rightSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "6", bottomBase: "1", squareRoot: false)])]
                )
            case .solveTwoStep:
                // x = 7
                return mathEquationBlueprint(
                    leftSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "x", bottomBase: "1", squareRoot: false)])],
                    relation: .equal,
                    rightSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "7", bottomBase: "1", squareRoot: false)])]
                )
            case .solveVariablesBothSides:
                // x = 3
                return mathEquationBlueprint(
                    leftSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "x", bottomBase: "1", squareRoot: false)])],
                    relation: .equal,
                    rightSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "3", bottomBase: "1", squareRoot: false)])]
                )
            case .solveWithFraction:
                // x = 15
                return mathEquationBlueprint(
                    leftSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "x", bottomBase: "1", squareRoot: false)])],
                    relation: .equal,
                    rightSide: [mathEquationBlueprint.Term(sign: .positive, factors: [mathEquationBlueprint.factor(topBase: "15", bottomBase: "1", squareRoot: false)])]
                )
            default:
                return mathEquationBlueprint(leftSide: [], relation: .equal, rightSide: [])
            }
        }
        
        var lightQuestion: lightQuestion {
            let answerString = self.questionType == .math ? "Math Blueprint Verification" : self.textAnswer
            return .init(questionWords: self.questionWords, answer: answerString)
        }
    }
}
