//
//  ChemistryUnit1.swift
//  Delta
//
//  Created by Desire on 2026-05-26.
// ai code

import SwiftUI
import Foundation
import Combine
import TestCreation

class ChemistryUnit1: Package, ObservableObject {
    func loadQuestion(descriptionOfQuestion: TestCreation.DescriptionOfQuestion) -> TestCreation.Question {
        createQuestion()
    }
    var publicName: String = "SNC1W Chemistry Unit"
    
    var internalName: String = "chemistryUnit1"
    
    var packageDescription: String = """
    This package covers the SNC1W/SNC1WE Grade 9 Chemistry Unit, including particle theory, physical/chemical properties, density math, the periodic table, Bohr-Rutherford/Lewis models, periodic trends, and ionic/covalent compounds.
    
    Not recommended for this to be the only study material.
    Generated by Gemini.
    """
    
    var id = UUID()
    
    @Published var allChangbleBools: [boolSetting] = [boolSetting(bool: false, name: "Randomize questions?")]
    
    @Published var numberOfQuestionsMadePerSection: Int = 30
    
    @Published var allChangbleInts: [intSetting] = [intSetting(int: 30, name: "Number of questions per section")]
    
    @Published var allChangbleDoubles: [doubleSetting] = []
  
    // Track the actual enum cases instead of lightQuestion structs so we keep the views attached
    var shuffledCases: [allQuestions] = []
    var randomizeQuestions: Bool = false
    var generatedAllCases: Bool = false
    var questionNum: Int = 0
    
    func updateInternalSettings() {
        numberOfQuestionsMadePerSection = allChangbleInts[0].int
        randomizeQuestions = allChangbleBools[0].bool
    }
    
    func createSection(numOfQuestions: Int) -> [TestCreation.Question] {
        var allQuestionsMade: [Question] = []
        let limit = min(numberOfQuestionsMadePerSection, loadAllCases().count)
        
        for _ in 0..<limit {
            allQuestionsMade.append(createQuestion())
        }
        questionNum = 0
        return allQuestionsMade
    }
    
    // Safely loads and shuffles the underlying enum cases
    func loadAllCases() -> [allQuestions] {
        if !generatedAllCases {
            shuffledCases = allQuestions.allCases
            generatedAllCases = true
        }
        
        if randomizeQuestions {
            shuffledCases.shuffle()
        } else {
            // Reset to default compiler order if randomization is turned off
            shuffledCases = allQuestions.allCases
        }
        
        return shuffledCases
    }
    
    // Fallback array loader required by your package protocols
    func loadAllQuestions() -> [lightQuestion] {
        var allQuestionsLoaded: [lightQuestion] = []
        for question in allQuestions.allCases {
            allQuestionsLoaded.append(question.lightQuestion)
        }
        return allQuestionsLoaded
    }
    
    func createQuestion() -> TestCreation.Question {
        let cases = loadAllCases()
        if cases.isEmpty {
            let emptyContent = QuestionContent { AnyView(VStack { Text("No questions loaded") }) }
            return Question(creator: self.id, questionName: "", questionText: "Empty", questionContent: emptyContent, questionContentSizeX: 500, questionContentSizeY: 500, questionAnswer: "None")
        }
        
        if self.questionNum >= cases.count {
            self.questionNum = 0
        }
        
        // 1. Grab the current case from our tracking array
        let currentCase = cases[questionNum]
        
        // 2. Create the real Question object directly from the enum case properties
        let trueQuestion = Question(
            creator: self.id, questionName: "",
            questionText: currentCase.questionWords,
            questionContent: currentCase.questionContent, // Injects the custom layout perfectly!
            questionContentSizeX: 500,
            questionContentSizeY: 500,
            questionAnswer: currentCase.answer
        )
        
        self.questionNum += 1
        return trueQuestion
    }
    
    func filterAnswer(answer: String) -> String {
        return answer.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
    }
    
    enum allQuestions: CaseIterable {
        // MARK: - Matter & Particle Theory
        case whatAreAtomsMadeOf
        case whatIsEverythingMadeOf
        case particleTheory
        case whatAreParticlesAlwaysDoing
        case whatIsMatter
        case statesOfMatter
        case characteristicsOfStates
        case changesOfStateList
        case whyAreCharacteristicsWhatTheyAre
        case stateChangesEnergy
        case pureSubstancesDef
        case pureSubstancesGroups
        case elementsDef
        case compoundsDef
        case mixtureDef
        case homogeneousMixtures
        case heterogeneousMixtures
        case howAreMixturesMade
        case hofbrinclMnemonic
        
        // MARK: - Properties & Changes
        case physicalPropertiesDef
        case quantitativePropertiesDef
        case qualitativePropertiesDef
        case physicalPropertiesList
        case chemicalPropertiesDef
        case chemicalPropertiesList
        case physicalVsChemicalChanges
        case physicalVsChemicalProperties
        case evidenceOfChemicalChange
        case flameTestColours
        
        // MARK: - Density Math
        case densityDef
        case densityFormula
        case densityCalcProblem1
        case densityCalcProblem2
        case densityCalcProblem3
        case densityCalcProblem4
        case densityCalcProblem5
        case densityCalcProblem6
        case densityOfWater
        case jupiterDensity
        
        // MARK: - Atomic Structure
        case atomicSymbols
        case particleCharges
        case readTableTopToBottom
        case determineNeutrons
        case drawBohrRutherford
        case valenceElectronsDef
        case valenceElectronsUsefulness
        case fillInTheBlankElectrons
        case lewisDotStructureDef
        case drawLewisCarbon
        case standardAtomicNotation
        case isotopeDef
        case whyAtomicMassDecimal
        case atomicNumberDef
        case atomicMassDef
        case atomicSymbolDef
        case carbonDating
        
        // MARK: - Periodic Table Overview
        case periodicTableDef
        case manMadeElementsCutoff
        case whyTableUseful
        case elementNamedAfterCreator
        case whyCalledPeriodicTable
        case whatIsWrongWithThisTable
        case threeBroadClasses
        case characteristicsOfThreeClasses
        case periodVsGroup
        case blankTableCategories
        case hydrogenAndHelium
        
        // MARK: - Ions & Bonding
        case ionDef
        case whatAtomsLoveValence
        case fillInBlankNeutral
        case cationVsAnion
        case lostLostElectronsCharge
        case fillInBlankRowsColumns
        case oxidationNumberDef
        case valenceNumberDef
        case oxidationTrend1To18
        case whatAtomsStriveToDo
        case howAtomsAchieveOctet
        case valenceDetermine
        case ionicCompoundDef
        case bondDef
        case ionicBondVsIonicCompound
        case howToKnowIfIonic
        case covalentBondDef
        case namingRulesDiff
        case namingIonicCompoundsRules
        case exampleNamingIonic
        
        // MARK: - Chemical Groups Characteristics
        case group1Characteristics
        case group2Characteristics
        case groups3To12Characteristics
        case metalloidsNotable
        case group17Characteristics
        case group18Characteristics
        case series6Characteristics
        case series7Characteristics
        case nonMetalsCharacteristics
        case postTransitionMetalsCharacteristics
        case nobleGasesCharacteristics
        
        // MARK: - Periodic Trends
        case atomicRadiusTrend
        case atomicRadiusDef
        case ionizationEnergyDef
        case ionizationEnergyTrend
        case electronegativityDef
        case electronegativityTrend
        case electronAffinityDef
        case electronAffinityTrend
        case meltingPointTrend
        case reactivityDef
        case reactivityTrend
        
        // MARK: - Gas Tests
        case gasTestsList

        var questionWords: String {
            switch self {
            case .whatAreAtomsMadeOf: return "What are atoms made of?"
            case .whatIsEverythingMadeOf: return "What is everything made of?"
            case .particleTheory: return "What is particle theory?"
            case .whatAreParticlesAlwaysDoing: return "What are particles always doing?"
            case .whatIsMatter: return "What is matter?"
            case .statesOfMatter: return "What are the states of matter?"
            case .characteristicsOfStates: return "What are the characteristics of each state of matter?"
            case .changesOfStateList: return "List all the possible changes in state of matter."
            case .whyAreCharacteristicsWhatTheyAre: return "Why are all the characteristics of each state of matter what they are?"
            case .stateChangesEnergy: return "What changes in state require energy and what lose energy?"
            case .pureSubstancesDef: return "What are pure substances?"
            case .pureSubstancesGroups: return "What are pure substances grouped into?"
            case .elementsDef: return "What are elements?"
            case .compoundsDef: return "What are compounds?"
            case .mixtureDef: return "What is a mixture?"
            case .homogeneousMixtures: return "What are homogeneous mixtures?"
            case .heterogeneousMixtures: return "What are heterogeneous mixtures?"
            case .howAreMixturesMade: return "How are these mixtures made?"
            case .hofbrinclMnemonic: return "What does HOFBrINCl stand for and why is it a helpful mnemonic?"
            case .physicalPropertiesDef: return "What are physical properties?"
            case .quantitativePropertiesDef: return "What are quantitative physical properties?"
            case .qualitativePropertiesDef: return "What are qualitative properties?"
            case .physicalPropertiesList: return "List the Qualitative and Quantitative physical properties in different groups and explain each."
            case .chemicalPropertiesDef: return "What are chemical properties?"
            case .chemicalPropertiesList: return "What are all the chemical properties listed in the google slides? Explain them."
            case .physicalVsChemicalChanges: return "Explain the difference between physical and chemical changes."
            case .physicalVsChemicalProperties: return "Explain the difference between physical and chemical properties."
            case .evidenceOfChemicalChange: return "What is the evidence that a chemical change has occurred?"
            case .flameTestColours: return "Why do flames turn different colours when metals are combusted in them?"
            case .densityDef: return "What is density?"
            case .densityFormula: return "What is the formula for density?"
            case .densityCalcProblem1: return "A sample of unknown metal has a mass of 0.0216kg and a volume of 8.00cm3. Calculate its density."
            case .densityCalcProblem2: return "My calculator has a mass of 67 kg and a volume 100cm3. What is its average density?"
            case .densityCalcProblem3: return "Amad weighs 1000 kg and has a density of 6.7 kg/cm3. What is his volume?"
            case .densityCalcProblem4: return "Mr. Amad’s car has a density of 67 kg/cm3 and a volume of 100 m3. What is its weight?"
            case .densityCalcProblem5: return "A balloon contains 5470 cm3 of gas and has a mass of 10240mg. If the mass of an empty balloon is 6.7g what is the gas’ density?"
            case .densityCalcProblem6: return "A scientist has developed a new type of material that is supposed to float on water. This material has a mass of 2.0g for every 3.0mL of volume. Will this material float on water? Explain."
            case .densityOfWater: return "What is the density of water?"
            case .jupiterDensity: return "Jupiter weighs around 1.9 septillion tonnes (1.9 * 10^24 kg) and has a volume of around 1.43 * 10^15 m3. What is Jupiter's density?"
            case .atomicSymbols: return "What are the atomic symbols for each “particle” in an atom?"
            case .particleCharges: return "Explain the charges of each “particle” in an atom."
            case .readTableTopToBottom: return "Explain how to read each part of an element card from top to bottom."
            case .determineNeutrons: return "Describe how you would determine the number of neutrons in an atom."
            case .drawBohrRutherford: return "Describe how you would draw the Bohr Rutherford model of an atom."
            case .valenceElectronsDef: return "What are valence electrons?"
            case .valenceElectronsUsefulness: return "Explain why valence electrons are useful?"
            case .fillInTheBlankElectrons: return "Fill in the blank: Electrons absorb energy and become ____ and _____ to _____ ____. The energy can then be released as _____."
            case .lewisDotStructureDef: return "Explain what the lewis dot structure is."
            case .drawLewisCarbon: return "Describe or draw a Lewis dot structure for Carbon."
            case .standardAtomicNotation: return "What is standard Atomic notation?"
            case .isotopeDef: return "Explain what an isotope is."
            case .whyAtomicMassDecimal: return "Explain why atomic masses are a weird decimal."
            case .atomicNumberDef: return "What is the atomic number?"
            case .atomicMassDef: return "What is the  atomic mass?"
            case .atomicSymbolDef: return "What is the atomic symbol?"
            case .carbonDating: return "Explain what radiometric/carbon dating is."
            case .periodicTableDef: return "What is the Periodic table?"
            case .manMadeElementsCutoff: return "At what atomic number where all elements above it are created by man?"
            case .whyTableUseful: return "Why is the periodic table useful for people and scientists?"
            case .elementNamedAfterCreator: return "What element is named after the creator of the Periodic Table?"
            case .whyCalledPeriodicTable: return "Why is the periodic table called what it is called?"
            case .whatIsWrongWithThisTable: return "Explain what is \"wrong with this table\" for Mr Langley."
            case .threeBroadClasses: return "What are the three broad classes of the periodic table?"
            case .characteristicsOfThreeClasses: return "What are the characteristics of the three broad classes?"
            case .periodVsGroup: return "What is a period and what is a group on the periodic table? What does each tell you?"
            case .blankTableCategories: return "What are the 10 different categories of elements found on the periodic table?"
            case .hydrogenAndHelium: return "What are the unique characteristics of hydrogen and helium?"
            case .ionDef: return "What is an ion?"
            case .whatAtomsLoveValence: return "What do atoms love, relating to valence electrons?"
            case .fillInBlankNeutral: return "Fill in the blank: Atoms are electrically ______"
            case .cationVsAnion: return "Explain the difference between a Cation and an Anion."
            case .lostLostElectronsCharge: return "If an atom has a -2 electrical charge how many electrons has it gained or lost?"
            case .fillInBlankRowsColumns: return "Fill in the blank: The elements on the periodic table are organized into ______ and _____"
            case .oxidationNumberDef: return "What does an element’s oxidation number tell?"
            case .valenceNumberDef: return "What does an element’s valence number tell?"
            case .oxidationTrend1To18: return "Explain what happens to an element’s oxidation number as you go from group 1 to 18. Explain each oxidation for each group."
            case .whatAtomsStriveToDo: return "What do atoms strive to do?"
            case .howAtomsAchieveOctet: return "How do atoms achieve a full valence shell?"
            case .valenceDetermine: return "What do the valence electrons determine?"
            case .ionicCompoundDef: return "What is an ionic compound?"
            case .bondDef: return "What is a bond?"
            case .ionicBondVsIonicCompound: return "Explain the difference between an Ionic bond and an Ionic compound."
            case .howToKnowIfIonic: return "How do you know if a compound is ionic or not?"
            case .covalentBondDef: return "What characteristics of a covalent bond hold atoms together in a molecular compound?"
            case .namingRulesDiff: return "How do the naming rules differ between ionic and covalent compounds?"
            case .namingIonicCompoundsRules: return "How do you name Ionic compounds?"
            case .exampleNamingIonic: return "How would you name the ionic compound NaCl or MgBr2?"
            case .group1Characteristics: return "What are the characteristics of group 1 of the periodic table?"
            case .group2Characteristics: return "What are the characteristics of group 2 of the periodic table?"
            case .groups3To12Characteristics: return "What are the characteristics of groups 3-12 of the periodic table?"
            case .metalloidsNotable: return "What is notable about the Metalloids?"
            case .group17Characteristics: return "What are the characteristics of group 17 of the periodic table?"
            case .group18Characteristics: return "What are the characteristics of group 18 of the periodic table?"
            case .series6Characteristics: return "What are the characteristics of special series 6 (Lanthanides) of the periodic table?"
            case .series7Characteristics: return "What are the characteristics of special series 7 (Actinides) of the periodic table?"
            case .nonMetalsCharacteristics: return "What are the characteristics of non-metals?"
            case .postTransitionMetalsCharacteristics: return "What are the characteristics of post-transition metals?"
            case .nobleGasesCharacteristics: return "What are the characteristics of Noble gases?"
            case .atomicRadiusTrend: return "Explain the Atomic Radius trend on the periodic table and why it happens."
            case .atomicRadiusDef: return "What is atomic radius?"
            case .ionizationEnergyDef: return "What is Ionization energy?"
            case .ionizationEnergyTrend: return "Explain the Ionization Energy trend on the periodic table and why it happens."
            case .electronegativityDef: return "What is Electronegativity?"
            case .electronegativityTrend: return "Explain the electronegativity trend on the periodic table and why it happens."
            case .electronAffinityDef: return "What is electron affinity?"
            case .electronAffinityTrend: return "Explain the electron affinity trend on the periodic table and why it happens."
            case .meltingPointTrend: return "Explain the melting point trend on the periodic table and why it happens."
            case .reactivityDef: return "What is reactivity?"
            case .reactivityTrend: return "Explain the reactivity trend on the periodic table and why it happens."
            case .gasTestsList: return "Describe the gas tests for Hydrogen (H2), Oxygen (O2), and Carbon Dioxide (CO2)."
            }
        }
        
        var questionContent: QuestionContent {
            switch self {
            case .standardAtomicNotation:
                return QuestionContent {
                    AnyView(
                        HStack(alignment: .center, spacing: 6) {
                            VStack(alignment: .trailing, spacing: 0) {
                                Text("A")
                                    .font(.system(size: 18, weight: .bold, design: .monospaced))
                                    .foregroundColor(.blue)
                                Text("Z")
                                    .font(.system(size: 14, weight: .medium, design: .monospaced))
                                    .foregroundColor(.red)
                            }
                            Text("X")
                                .font(.system(size: 36, weight: .black, design: .rounded))
                        }
                        .padding()
                    )
                }
                
            case .drawLewisCarbon:
                return QuestionContent {
                    AnyView(
                        VStack(spacing: 8) {
                            Text("Workspace Diagram Hint:")
                                .font(.caption).foregroundColor(.secondary)
                            HStack(spacing: 16) {
                                Circle().fill(Color.blue).frame(width: 6, height: 6)
                                Text("C").font(.title).bold()
                                Circle().fill(Color.blue).frame(width: 6, height: 6)
                            }
                        }
                        .padding(8)
                        .background(Color(.secondarySystemFill))
                        .cornerRadius(8)
                    )
                }
                
            case .densityFormula:
                return QuestionContent {
                    AnyView(
                        VStack(spacing: 4) {
                            Text("D = m / V")
                                .font(.system(.headline, design: .monospaced))
                                .padding(10)
                                .background(Color.accentColor.opacity(0.1))
                                .cornerRadius(6)
                        }
                    )
                }
                
            case .densityCalcProblem1, .densityCalcProblem2, .densityCalcProblem3, .densityCalcProblem4, .densityCalcProblem5, .densityCalcProblem6, .jupiterDensity:
                return QuestionContent {
                    AnyView(
                        HStack(spacing: 12) {
                            Image(systemName: "pencil.and.ruler.fill")
                                .foregroundColor(.accentColor)
                            Text("Scratchpad: Write out your Given, Find, and Formula steps before submitting your final value calculation.")
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                        .padding(10)
                        .background(Color(.secondarySystemFill))
                        .cornerRadius(8)
                    )
                }
                
            case .drawBohrRutherford:
                return QuestionContent {
                    AnyView(
                        VStack(spacing: 6) {
                            Text("Bohr-Rutherford Max Shell Capacity:")
                                .font(.caption).bold()
                            Text("Shell 1: 2e⁻  |  Shell 2: 8e⁻  |  Shell 3: 8e⁻")
                                .font(.caption).foregroundColor(.secondary)
                        }
                        .padding(8)
                        .background(Color(.secondarySystemFill))
                        .cornerRadius(6)
                    )
                }
                
            default:
                return QuestionContent {
                    AnyView(VStack { })
                }
            }
        }
        
        var answer: String {
            switch self {
            case .whatAreAtomsMadeOf:
                return "Protons, neutrons, and electrons."
            case .whatIsEverythingMadeOf:
                return "Matter, which is composed of atoms."
            case .particleTheory:
                return "A theory stating: 1. All matter is made of tiny particles. 2. All particles of one substance are identical. 3. Particles have spaces between them. 4. Particles are always moving. 5. Particles attract each other."
            case .whatAreParticlesAlwaysDoing:
                return "Moving or vibrating constantly."
            case .whatIsMatter:
                return "Anything that has mass and takes up space (volume)."
            case .statesOfMatter:
                return "Solid, liquid, and gas."
            case .characteristicsOfStates:
                return "Solids: Fixed shape and volume, tightly packed particles. Liquids: Fixed volume but take the shape of their container, close but sliding particles. Gases: No fixed shape or volume, widely spaced particles moving rapidly."
            case .changesOfStateList:
                return "Melting, Freezing, Evaporation, Condensation, Sublimation (solid to gas), and Deposition (gas to solid)."
            case .whyAreCharacteristicsWhatTheyAre:
                return "Because of the balance between the kinetic energy of the particles (moving them apart) and the attractive forces pulling them together."
            case .stateChangesEnergy:
                return "Require energy (Endothermic): Melting, Evaporation, Sublimation. Lose energy (Exothermic): Freezing, Condensation, Deposition."
            case .pureSubstancesDef:
                return "Matter made up of only one type of particle."
            case .pureSubstancesGroups:
                return "Elements and Compounds."
            case .elementsDef:
                return "Pure substances that cannot be broken down into simpler substances (e.g., Oxygen, Gold). Made of only one type of atom."
            case .compoundsDef:
                return "Pure substances made of two or more different elements chemically bonded in fixed proportions (e.g., H2O, CO2)."
            case .mixtureDef:
                return "A physical combination of two or more substances that are not chemically bonded together."
            case .homogeneousMixtures:
                return "Mixtures that look uniform throughout; you can only see one phase (e.g., salt water, apple juice)."
            case .heterogeneousMixtures:
                return "Mixtures where the different components are visually distinguishable; you can see multiple phases (e.g., salad, oil and water)."
            case .howAreMixturesMade:
                return "By physically blending elements or compounds together without creating any chemical bonds."
            case .hofbrinclMnemonic:
                return "Hydrogen, Oxygen, Fluorine, Bromine, Iodine, Nitrogen, Chlorine. It helps remember the 7 diatomic elements that naturally exist in pairs."
            case .physicalPropertiesDef:
                return "A characteristic of a substance that can be observed or measured without changing its chemical identity."
            case .quantitativePropertiesDef:
                return "Physical properties that can be measured and expressed with numbers/units."
            case .qualitativePropertiesDef:
                return "Physical properties observed using senses that do not involve numerical measurements."
            case .physicalPropertiesList:
                return "Qualitative: State, Colour, Odour, Texture, Lustre (shininess), Malleability (ability to hammer into sheets), Ductility (ability to pull into wires), Clarity. Quantitative: Density, Melting Point, Boiling Point, Solubility, Viscosity, Hardness."
            case .chemicalPropertiesDef:
                return "A characteristic of a substance that describes its ability to undergo a specific chemical change to form a new substance."
            case .chemicalPropertiesList:
                return "Combustibility (burns in oxygen), Reactivity with water/acid, Toxicity, Stability, and Corrosivity. They describe how a substance behaves during a reaction."
            case .physicalVsChemicalChanges:
                return "A physical change alters form or state but retains original chemical composition (e.g., melting ice). A chemical change forms completely new chemical substances with distinct properties (e.g., rusting iron)."
            case .physicalVsChemicalProperties:
                return "Physical properties can be observed without altering the substance's chemical structure. Chemical properties can only be observed by changing the substance's identity through a reaction."
            case .evidenceOfChemicalChange:
                return "1. Unexpected colour change. 2. Gas production (bubbles). 3. Precipitate forms (solid forms from two liquids). 4. Heat or light is released/absorbed. 5. Irreversibility."
            case .flameTestColours:
                return "Electrons absorb thermal energy, jumping to a higher excited energy level. When they drop back down to their stable ground state, they release that trapped energy as light of a specific wavelength/colour."
            case .densityDef:
                return "The mass of a substance contained within a unit volume."
            case .densityFormula:
                return "Density = Mass / Volume (D = m/V)"
            case .densityCalcProblem1:
                return "0.0216 kg = 21.6 g. Density = 21.6g / 8.00cm3 = 2.7 g/cm3."
            case .densityCalcProblem2:
                return "Density = 67kg / 100cm3 = 0.67 kg/cm3."
            case .densityCalcProblem3:
                return "Volume = Mass / Density = 1000kg / (6.7 kg/cm3) = 149.25 cm3."
            case .densityCalcProblem4:
                return "Mass = Density * Volume = 67 kg/cm3 * 100 m3. Converting units: 100 m3 = 100,000,000 cm3. Mass = 67 * 100,000,000 = 6,700,000,000 kg."
            case .densityCalcProblem5:
                return "Total Mass = 10240 mg = 10.24 g. Mass of gas = 10.24g - 6.7g = 3.54 g. Density = 3.54g / 5470cm3 = 0.000647 g/cm3."
            case .densityCalcProblem6:
                return "Density = 2.0g / 3.0mL = 0.67 g/mL. Yes, it floats because its density is less than the density of water (1.0 g/mL)."
            case .densityOfWater:
                return "1.0 g/mL (or 1.0 g/cm3)."
            case .jupiterDensity:
                return "Density = Mass / Volume = (1.9 * 10^24 kg) / (1.43 * 10^15 m3) = 1,328,671,328 kg/m3."
            case .atomicSymbols:
                return "Proton: p+, Neutron: n0, Electron: e-."
            case .particleCharges:
                return "Protons are positive (+1), Neutrons are neutral (0), Electrons are negative (-1)."
            case .readTableTopToBottom:
                return "Top: Atomic Number. Middle: Atomic Symbol & Element Name. Bottom: Atomic Mass."
            case .determineNeutrons:
                return "Subtract the Atomic Number from the rounded Atomic Mass (Neutrons = Mass - Number)."
            case .drawBohrRutherford:
                return "1. Find protons and neutrons and write them inside a central nucleus circle. 2. Find electrons (equal to protons). 3. Draw concentric electron shells outward: max 2 in first shell, 8 in second, 8 in third."
            case .valenceElectronsDef:
                return "The electrons residing in the outermost shell of an atom."
            case .valenceElectronsUsefulness:
                return "They dictate chemical bonding properties, reactivity patterns, and how atoms combine with other elements."
            case .fillInTheBlankElectrons:
                return "excited, jump, higher shells, light"
            case .lewisDotStructureDef:
                return "A simplified atomic diagram that shows only the element's chemical symbol surrounded by dots representing its valence electrons."
            case .drawLewisCarbon:
                return "Write the symbol 'C' surrounded by 4 single dots (one on each of the top, bottom, left, and right sides)."
            case .standardAtomicNotation:
                return "A shorthand representation showing the element symbol with the Atomic Mass written as a superscript on the top left and the Atomic Number as a subscript on the bottom left."
            case .isotopeDef:
                return "Atoms of the same element that have the identical number of protons but a different number of neutrons, changing their mass."
            case .whyAtomicMassDecimal:
                return "It is a weighted average calculated across all naturally occurring isotopes of that element based on their environmental abundance."
            case .atomicNumberDef:
                return "The total number of protons found in the nucleus of an atom; it defines the element's identity."
            case .atomicMassDef:
                return "The total mass of protons and neutrons combined inside an atom's nucleus."
            case .atomicSymbolDef:
                return "A 1- or 2-letter universal abbreviation assigned to an element."
            case .carbonDating:
                return "A scientific technique used to determine the age of organic materials by measuring the radioactive decay rate of the unstable Carbon-14 isotope."
            case .periodicTableDef:
                return "An organized chart of chemical elements structured by increasing atomic number, displaying recurring chemical and physical properties."
            case .manMadeElementsCutoff:
                return "Atomic number 93 (Neptunium) and above are synthetic/man-made elements. Uranium (92) is the heaviest naturally occurring element."
            case .whyTableUseful:
                return "It organizes elements logically, allowing scientists to instantly predict how an element will react, bond, and look based on its position."
            case .elementNamedAfterCreator:
                return "Mendelevium (Md), named after Dmitri Mendeleev."
            case .whyCalledPeriodicTable:
                return "Because properties repeat in cycles or regular intervals ('periods') across rows."
            case .whatIsWrongWithThisTable:
                return "Hydrogen is grouped with highly reactive alkali metals despite being a gas, and Helium has a full valence shell of 2 but sits with group 18 elements which have 8 valence electrons."
            case .threeBroadClasses:
                return "Metals, Non-metals, and Metalloids."
            case .characteristicsOfThreeClasses:
                return "Metals: Shiny, malleable, ductile, good conductors. Non-metals: Dull, brittle, poor conductors, mostly gases. Metalloids: Properties intermediate between metals and non-metals, semi-conductors."
            case .periodVsGroup:
                return "Period: A horizontal row; indicates the number of electron shells. Group: A vertical column; indicates elements share the same number of valence electrons and chemical behaviors."
            case .blankTableCategories:
                return "Alkali Metals, Alkaline Earth Metals, Transition Metals, Post-Transition Metals, Metalloids, Non-Metals, Halogens, Noble Gases, Lanthanides, Actinides."
            case .hydrogenAndHelium:
                return "Hydrogen behaves like a non-metal but sits over group 1 because it has 1 valence electron. Helium behaves like a noble gas but only requires 2 valence electrons to fill its outer shell completely."
            case .ionDef:
                return "A charged atom formed by losing or gaining valence electrons."
            case .whatAtomsLoveValence:
                return "Having a completely full outer valence electron shell (stable octet)."
            case .fillInBlankNeutral:
                return "neutral"
            case .cationVsAnion:
                return "Cations are positively charged ions formed by losing electrons (metals). Anions are negatively charged ions formed by gaining electrons (non-metals)."
            case .lostLostElectronsCharge:
                return "It has GAINED 2 electrons (since electrons carry negative charges)."
            case .fillInBlankRowsColumns:
                return "periods, groups"
            case .oxidationNumberDef:
                return "The net electrical charge an atom obtains when it gains or loses electrons to become stable."
            case .valenceNumberDef:
                return "The total number of electrons an atom must gain, lose, or share to reach a stable configuration."
            case .oxidationTrend1To18:
                return "Group 1: +1, Group 2: +2, Group 13: +3, Group 14: +/-4, Group 15: -3, Group 16: -2, Group 17: -1, Group 18: 0."
            case .whatAtomsStriveToDo:
                return "Achieve structural stability by filling their valence electron shells."
            case .howAtomsAchieveOctet:
                return "By transferring electrons (ionic bonding) or sharing electrons (covalent bonding)."
            case .valenceDetermine:
                return "Reactivity patterns, chemical bonding affinity, and the atomic ratios in formulas."
            case .ionicCompoundDef:
                return "A chemical compound composed of positive ions (metals) and negative ions (non-metals) bound tightly together by electrostatic attraction."
            case .bondDef:
                return "A powerful electrostatic attraction link holding atoms or ions together."
            case .ionicBondVsIonicCompound:
                return "An ionic bond is the chemical link formed by electron transfer. An ionic compound is the bulk macroscopic crystal structure resulting from those bonds."
            case .howToKnowIfIonic:
                return "Check the formula: if it combines a metal with a non-metal, it is an ionic compound."
            case .covalentBondDef:
                return "An attraction formed when two non-metal atoms share pairs of valence electrons to build stable configurations."
            case .namingRulesDiff:
                return "Ionic compounds name the metal then the non-metal ending in '-ide' without numerical prefixes. Covalent compounds use Greek prefixes (mono, di, tri) to specify exactly how many atoms of each non-metal are present."
            case .namingIonicCompoundsRules:
                return "1. Write the full name of the metal first. 2. Write the non-metal second, changing its ending suffix to '-ide'."
            case .exampleNamingIonic:
                return "NaCl is Sodium Chloride. MgBr2 is Magnesium Bromide."
            case .group1Characteristics:
                return "Alkali Metals: Highly reactive, soft, silver metals with 1 valence electron."
            case .group2Characteristics:
                return "Alkaline Earth Metals: Light, reactive metals with 2 valence electrons."
            case .groups3To12Characteristics:
                return "Transition Metals: Hard, dense, structural metals with complex electron configurations."
            case .metalloidsNotable:
                return "They form a diagonal staircase line dividing metals and non-metals, possessing properties from both classes."
            case .group17Characteristics:
                return "Halogens: Highly reactive, toxic non-metals with 7 valence electrons."
            case .group18Characteristics:
                return "Noble Gases: Completely unreactive, colorless, odorless gases with full valence shells."
            case .series6Characteristics:
                return "Lanthanides: Shiny, reactive transition elements often called rare earth metals."
            case .series7Characteristics:
                return "Actinides: Radioactive elements; most are synthetic."
            case .nonMetalsCharacteristics:
                return "Poor conductors, brittle solids or gases, lack metallic lustre."
            case .postTransitionMetalsCharacteristics:
                return "Softer, weaker metals located between transition metals and metalloids."
            case .nobleGasesCharacteristics:
                return "Chemical stability prevents them from forming bonds naturally."
            case .atomicRadiusTrend:
                return "Decreases moving left-to-right across a period due to increased positive nuclear charge pulling electrons inward. Increases moving top-to-bottom down a group because new electron shells are being added."
            case .atomicRadiusDef:
                return "The total distance measured from the center of an atom's nucleus to its outermost stable electron valence shell."
            case .ionizationEnergyDef:
                return "The total energy package required to successfully strip away a loosely bound electron from a gas atom."
            case .ionizationEnergyTrend:
                return "Increases moving left-to-right due to strong nuclear pull holding valence shells tightly. Decreases moving top-to-bottom because outer electrons sit farther from the nucleus, shielded by inner shells."
            case .electronegativityDef:
                return "An atom's relative pulling power to attract shared bonding electrons toward itself."
            case .electronegativityTrend:
                return "Increases moving left-to-right as atoms approach an octet structure. Decreases moving top-to-bottom because structural electron shielding dampens nuclear pull."
            case .electronAffinityDef:
                return "The net energy shift occurring when an electron is integrated into a gaseous atom."
            case .electronAffinityTrend:
                return "Generally increases across a period as elements want to fill their valence shells, and decreases going down a group."
            case .meltingPointTrend:
                return "For metals, melting points generally decrease going down a group. For non-metals (like halogens), melting points increase going down a group."
            case .reactivityDef:
                return "The relative speed and ease with which an element undergoes chemical transformations."
            case .reactivityTrend:
                return "Metals: Reactivity increases down a group and left across a period (easier to lose electrons). Non-metals: Reactivity increases up a group and right across a period (easier to pull electrons in)."
            case .gasTestsList:
                return "Hydrogen: Bring a burning splint near the gas; it will make a distinctive 'pop' sound. Oxygen: Bring a glowing splint into the gas; the splint will reignite into a flame. Carbon Dioxide: Bubble the gas into limewater; the liquid turns cloudy/milky, or it will extinguish a burning splint."
            }
        }
        
        var lightQuestion: lightQuestion {
            return .init(questionWords: self.questionWords, answer: self.answer)
        }
    }
}
