//
//  NumberSetsUnit.swift
//  Delta
//
//  Created by Desire on 2026-06-01.
//


import SwiftUI
import Foundation
import Combine
import TestCreation

class NumberSetsUnit: Package, ObservableObject {
    
    var publicName: String = "Number Sets & Mathematical Notation"
    
    var internalName: String = "numberSetsUnit"
    
    var packageDescription: String = """
    This package covers standard mathematical number sets, including Natural, Whole, Integers, Rational, Irrational, and Real numbers, alongside their universal symbolic notations.
    Generated by Gemini.
    """
    
    var id = UUID()
    
    @Published var allChangbleBools: [boolSetting] = [boolSetting(bool: false, name: "Randomize questions?")]
    
    @Published var numberOfQuestionsMadePerSection: Int = 12
    
    @Published var allChangbleInts: [intSetting] = [intSetting(int: 12, name: "Number of questions per section")]
    
    @Published var allChangbleDoubles: [doubleSetting] = []
  
    var shuffledCases: [allQuestions] = []
    var randomizeQuestions: Bool = false
    var generatedAllCases: Bool = false
    var questionNum: Int = 0
    
    func updateInternalSettings() {
        numberOfQuestionsMadePerSection = allChangbleInts[0].int
        randomizeQuestions = allChangbleBools[0].bool
    }
    
    func createSection(numOfQuestions: Int) -> [TestCreation.Question] {
        var allQuestionsMade: [Question] = []
        let limit = min(numberOfQuestionsMadePerSection, loadAllCases().count)
        
        for _ in 0..<limit {
            allQuestionsMade.append(createQuestion())
        }
        questionNum = 0
        return allQuestionsMade
    }
    
    func loadAllCases() -> [allQuestions] {
        if !generatedAllCases {
            shuffledCases = allQuestions.allCases
            generatedAllCases = true
        }
        
        if randomizeQuestions {
            shuffledCases.shuffle()
        } else {
            shuffledCases = allQuestions.allCases
        }
        
        return shuffledCases
    }
    
    func loadAllQuestions() -> [lightQuestion] {
        var allQuestionsLoaded: [lightQuestion] = []
        for question in allQuestions.allCases {
            allQuestionsLoaded.append(question.lightQuestion)
        }
        return allQuestionsLoaded
    }
    
    func createQuestion() -> TestCreation.Question {
        let cases = loadAllCases()
        if cases.isEmpty {
            let emptyContent = QuestionContent { VStack { Text("No questions loaded") } }
            return Question(creator: self.id, questionType: .text, questionText: "Empty", questionContent: emptyContent, questionContentSizeX: 500, questionContentSizeY: 500, questionAnswer: "None")
        }
        
        if self.questionNum >= cases.count {
            self.questionNum = 0
        }
        
        let currentCase = cases[questionNum]
        
        let trueQuestion = Question(
            creator: self.id,
            questionType: .text,
            questionText: currentCase.questionWords,
            questionContent: currentCase.questionContent,
            questionContentSizeX: 500,
            questionContentSizeY: 500,
            questionAnswer: currentCase.answer
        )
        
        self.questionNum += 1
        return trueQuestion
    }
    
    func filterAnswer(answer: String) -> String {
        // Fixed the spelling from trimimmingCharacters -> trimmingCharacters
        return answer.uppercased().trimmingCharacters(in: .whitespacesAndNewlines)
    }
    
    enum allQuestions: CaseIterable {
        // MARK: - Symbol Recognition
        case symbolNatural
        case symbolWhole
        case symbolIntegers
        case symbolRational
        case symbolIrrational
        case symbolReal
        
        // MARK: - Definition & Membership
        case defNatural
        case defWhole
        case defIntegers
        case checkZeroWhole
        case checkNegativeInteger
        case checkPiIrrational

        var questionWords: String {
            switch self {
            case .symbolNatural: return "What bold or double-struck capital letter represents the set of Natural numbers?"
            case .symbolWhole: return "What capital letter symbol is commonly used to represent the set of Whole numbers?"
            case .symbolIntegers: return "What capital letter symbol represents the set of Integers?"
            case .symbolRational: return "What capital letter symbol represents the set of Rational numbers?"
            case .symbolIrrational: return "What symbol is commonly used for Irrational numbers?"
            case .symbolReal: return "What bold or double-struck capital letter represents the set of all Real numbers?"
            case .defNatural: return "True or False: Natural numbers (counting numbers) include the number 0."
            case .defWhole: return "What is the primary difference between the set of Natural numbers and the set of Whole numbers?"
            case .defIntegers: return "Does the set of Integers include fractional values or decimals like 2.5?"
            case .checkZeroWhole: return "Is the number 0 a member of the set of Whole numbers? (Yes or No)"
            case .checkNegativeInteger: return "Is -5 a member of the set of Natural numbers, Whole numbers, or Integers?"
            case .checkPiIrrational: return "Is the mathematical constant Pi (π) a Rational or Irrational number?"
            }
        }
        
        var questionContent: QuestionContent {
            switch self {
            case .symbolNatural, .defNatural:
                return QuestionContent {
                    Text("{1, 2, 3, 4, ...}")
                        .font(.system(.title2, design: .monospaced)).bold()
                        .padding(8)
                        .background(Color(.secondarySystemFill))
                        .cornerRadius(6)
                }
            case .symbolWhole, .defWhole, .checkZeroWhole:
                return QuestionContent {
                    Text("{0, 1, 2, 3, ...}")
                        .font(.system(.title2, design: .monospaced)).bold()
                        .padding(8)
                        .background(Color(.secondarySystemFill))
                        .cornerRadius(6)
                }
            case .symbolIntegers, .defIntegers, .checkNegativeInteger:
                return QuestionContent {
                    Text("{..., -3, -2, -1, 0, 1, 2, ...}")
                        .font(.system(.title2, design: .monospaced)).bold()
                        .padding(8)
                        .background(Color(.secondarySystemFill))
                        .cornerRadius(6)
                }
            case .symbolRational:
                return QuestionContent {
                    Text("{ a/b | a, b ∈ Z, b ≠ 0 }")
                        .font(.system(.title3, design: .monospaced)).bold()
                        .padding(8)
                        .background(Color(.secondarySystemFill))
                        .cornerRadius(6)
                }
            case .symbolIrrational, .checkPiIrrational:
                return QuestionContent {
                    Text("π,  √2,  e")
                        .font(.system(.title2, design: .serif)).italic().bold()
                        .padding(8)
                        .background(Color(.secondarySystemFill))
                        .cornerRadius(6)
                }
            default:
                return QuestionContent {
                    HStack(spacing: 8) {
                        Image(systemName: "number.square.fill")
                            .foregroundColor(.accentColor)
                        Text("Number Systems Classification")
                            .font(.caption).bold()
                    }
                }
            }
        }
        
        var answer: String {
            switch self {
            case .symbolNatural: return "N"
            case .symbolWhole: return "W"
            case .symbolIntegers: return "Z"
            case .symbolRational: return "Q"
            case .symbolIrrational: return "Q'" // Filters fallback or checks can capture alternatives
            case .symbolReal: return "R"
            case .defNatural: return "FALSE"
            case .defWhole: return "Whole numbers include zero (0), while natural numbers do not."
            case .defIntegers: return "NO"
            case .checkZeroWhole: return "YES"
            case .checkNegativeInteger: return "INTEGERS"
            case .checkPiIrrational: return "IRRATIONAL"
            }
        }
        
        var lightQuestion: lightQuestion {
            return .init(questionWords: self.questionWords, answer: self.answer)
        }
    }
}
