//
//  PolynomialPackage.swift
//  Delta
//
//  Created by Desire on 2026-05-26.
//


import Foundation
import SwiftUI
import Combine
import TestCreation

class PolynomialPackage: ObservableObject, Package {
    func loadQuestion(descriptionOfQuestion: TestCreation.DescriptionOfQuestion) -> TestCreation.Question {
        createQuestion()
    }
    

    // MARK: Identity
    let id = UUID()

    let publicName = "Polynomials"
    let internalName = "polynomial_generator"

    var packageDescription = "Generates random polynomial expansion and simplification questions. Generated by ChatGPT."

    // MARK: Settings
    var allChangbleBools: [boolSetting] = [
        boolSetting(bool: true, name: "Expand Brackets"),
        boolSetting(bool: true, name: "Simplify Expressions")
    ]

    var allChangbleInts: [intSetting] = [
        intSetting(int: 1, name: "Difficulty")
    ]

    var allChangbleDoubles: [doubleSetting] = []

    // MARK: Required
    func updateInternalSettings() {}

    func createSection(numOfQuestions: Int) -> [Question] {
        (0..<numOfQuestions).map { _ in createQuestion() }
    }

    func createQuestion() -> Question {

        let difficulty = allChangbleInts.first?.int ?? 1
        let allowExpand = allChangbleBools.first?.bool ?? true

        if allowExpand && Bool.random() {
            return generateExpansion(difficulty: difficulty)
        } else {
            return generateSimplification(difficulty: difficulty)
        }
    }

    // MARK: Random polynomial expansion
    private func generateExpansion(difficulty: Int) -> Question {

        let a = Int.random(in: 1...5)
        let b = Int.random(in: 1...5)
        let x = "x"

        let question = "(\(a)x + \(b))(\(x + String(Int.random(in: 1...3))))"

        let answer = "\(a)x² + \(a * Int.random(in: 1...3) + b)x + \(b * Int.random(in: 1...3))"

        return Question(
            creator: id, questionName: "",
            questionType: .text,
            questionText: "Expand: \(question)",
            questionContent: QuestionContent {
                VStack {
                    Text("Polynomial Expansion")
                        .font(.headline)
                    Text(question)
                        .font(.title2)
                }
            },
            questionContentSizeX: 300,
            questionContentSizeY: 150,
            questionAnswer: answer
        )
    }

    // MARK: Random simplification
    private func generateSimplification(difficulty: Int) -> Question {

        let a = Int.random(in: 1...10)
        let b = Int.random(in: 1...10)
        let c = Int.random(in: 1...5)

        let question = "\(a)x + \(b)x + \(c)"

        let simplified = "\(a + b)x + \(c)"

        return Question(
            creator: id, questionName: "",
            questionType: .text,
            questionText: "Simplify: \(question)",
            questionContent: QuestionContent {
                VStack {
                    Text("Polynomial Simplification")
                        .font(.headline)
                    Text(question)
                        .font(.title2)
                }
            },
            questionContentSizeX: 300,
            questionContentSizeY: 150,
            questionAnswer: simplified
        )
    }

    // MARK: Answer filter
    func filterAnswer(answer: String) -> String {
        answer
            .replacingOccurrences(of: " ", with: "")
            .lowercased()
    }
}
