//
//  TrigonometryPackage.swift
//  Delta
//
//  Created by Desire on 2026-05-26.
//


import Foundation
import SwiftUI
import Combine
import TestCreation

 class TrigonometryPackage: ObservableObject, Package {

    // MARK: Identity
    let id = UUID()

    let publicName = "Trigonometry"
    let internalName = "trigonometry"

    var packageDescription = "Basic trig questions using SOH-CAH-TOA and unit circle values. Generated By ChatGPT"

    // MARK: Settings
    var allChangbleBools: [boolSetting] = [
        boolSetting(bool: true, name: "SOHCAHTOA"),
        boolSetting(bool: true, name: "Unit Circle")
    ]

    var allChangbleInts: [intSetting] = [
        intSetting(int: 1, name: "Difficulty")
    ]

    var allChangbleDoubles: [doubleSetting] = []

    // MARK: Required
    func updateInternalSettings() {}

    func createSection(numOfQuestions: Int) -> [Question] {
        (0..<numOfQuestions).map { _ in createQuestion() }
    }

    func createQuestion() -> Question {

        let useSOH = allChangbleBools.first?.bool ?? true
        let difficulty = allChangbleInts.first?.int ?? 1

        if useSOH && Bool.random() {
            return makeSOHCAHTOA(difficulty: difficulty)
        } else {
            return makeUnitCircle(difficulty: difficulty)
        }
    }

    // MARK: SOHCAHTOA
    private func makeSOHCAHTOA(difficulty: Int) -> Question {

        let angle = [30, 45, 60].randomElement()!
        let type = ["sin", "cos", "tan"].randomElement()!

        let answer: String

        switch (type, angle) {
        case ("sin", 30): answer = "1/2"
        case ("sin", 45): answer = "√2/2"
        case ("sin", 60): answer = "√3/2"

        case ("cos", 30): answer = "√3/2"
        case ("cos", 45): answer = "√2/2"
        case ("cos", 60): answer = "1/2"

        case ("tan", 30): answer = "√3/3"
        case ("tan", 45): answer = "1"
        case ("tan", 60): answer = "√3"

        default: answer = "0"
        }

        return Question(
            creator: id,
            questionType: .text,
            questionText: "What is \(type)(\(angle)°)?",
            questionContent: QuestionContent {
                AnyView(
                    VStack {
                        Text("Trigonometry")
                            .font(.headline)
                        Text("\(type)(\(angle)°)")
                            .font(.title3)
                    }
                )
            },
            questionContentSizeX: 300,
            questionContentSizeY: 150,
            questionAnswer: answer
        )
    }

    // MARK: Unit Circle
    private func makeUnitCircle(difficulty: Int) -> Question {

        let angle = [0, 30, 45, 60, 90, 180].randomElement()!

        let answer: String

        switch angle {
        case 0: answer = "1"
        case 30: answer = "√3/2"
        case 45: answer = "√2/2"
        case 60: answer = "1/2"
        case 90: answer = "0"
        case 180: answer = "-1"
        default: answer = "0"
        }

        return Question(
            creator: id,
            questionType: .text,
            questionText: "What is cos(\(angle)°)?",
            questionContent: QuestionContent {
                AnyView(
                    VStack {
                        Text("Unit Circle")
                            .font(.headline)
                        Text("cos(\(angle)°)")
                            .font(.title2)
                    }
                )
            },
            questionContentSizeX: 300,
            questionContentSizeY: 150,
            questionAnswer: answer
        )
    }

    // MARK: Answer Filter
    func filterAnswer(answer: String) -> String {
        answer
            .replacingOccurrences(of: " ", with: "")
            .lowercased()
    }
}
